In [1]:
import matplotlib.pyplot as plt
# 한글처리
import matplotlib as mpl
mpl.rc('font',family='Malgun Gothic')
import seaborn as sns
import pandas as pd
import scipy.stats as stats

In [2]:
df_ROS = pd.read_csv('./dataset/RecurrenceOfSurgery.csv')
df_ROS.head(2)

,Unnamed: 0,환자ID,Large Lymphocyte,Location of herniation,ODI,가족력,간질성폐질환,고혈압여부,과거수술횟수,당뇨여부,...,Modic change,PI,PT,Seg Angle(raw),Vaccum disc,골밀도,디스크단면적,디스크위치,척추이동척도,척추전방위증
0,0,1PT,22.8,3,51.0,0.0,0,0,0,0,...,3,51.6,36.6,14.4,0,-1.01,2048.5,4,Down,0
1,1,2PT,44.9,4,26.0,0.0,0,0,0,0,...,0,40.8,7.2,17.8,0,-1.14,1753.1,4,Up,0

In [4]:
df_ROS_forpatient = df_ROS[['고혈압여부', '당뇨여부', '성별', '스테로이드치료', '신장', '심혈관질환', '연령', '입원기간', '체중', '환자통증정도', '수술시간', '재발여부']]
df_ROS_forpatient

      고혈압여부  당뇨여부  성별  스테로이드치료   신장  심혈관질환  연령  입원기간    체중  환자통증정도  수술시간  재발여부
0         0     0   2        1  163      0  66     2  60.3      10  68.0     0
1         0     0   1        1  171      0  47     1  71.7      10  31.0     0
2         0     0   1        1  178      0  39     1  77.1       7  78.0     0
3         1     0   1        0  174      0  40     1  74.2       7  73.0     0
4         1     0   1        1  183      0  42     2  80.7       7  29.0     0
...     ...   ...  ..      ...  ...    ...  ..   ...   ...     ...   ...   ...
1889      0     0   2        1  157      0  59     2  64.0       7  80.0     0
1890      0     0   2        1  157      0  42     4  59.0       7  20.0     0
1891      0     0   1        1  167      0  61     3  70.0       7  50.0     0
1892      0     0   1        1  177      0  29     4  77.0       7  25.0     0
1893      0     0   2        1  168      0  30     2  49.0       8  45.0     0

[1894 rows x 12 columns]

In [5]:
# null값 찾기 - 결과) 수술시간 54개의 null값 존재
df_ROS_forpatient.isnull().sum()

고혈압여부       0
당뇨여부        0
성별          0
스테로이드치료     0
신장          0
심혈관질환       0
연령          0
입원기간        0
체중          0
환자통증정도      0
수술시간       54
재발여부        0
dtype: int64

In [7]:
df_ROS_forpatient = df_ROS_forpatient.dropna().copy()

In [8]:
df_ROS_forpatient.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1840 entries, 0 to 1893
Data columns (total 12 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   고혈압여부    1840 non-null   int64
 1   당뇨여부     1840 non-null   int64
 2   성별       1840 non-null   int64
 3   스테로이드치료  1840 non-null   int64
 4   신장       1840 non-null   int64
 5   심혈관질환    1840 non-null   int64
 6   연령       1840 non-null   int64
 7   입원기간     1840 non-null   int64
 8   체중       1840 non-null   float64
 9   환자통증정도   1840 non-null   int64
 10  수술시간     1840 non-null   float64
 11  재발여부     1840 non-null   int64
dtypes: float64(2), int64(10)
memory usage: 186.9 KB

In [ ]:
df